//! Downstream contract fixtures (IMPLEMENTATION-PLAN risk table: "add a
//! contract test in the hypervisor repo against burst fixtures from this
//! repo's testdata/").
//!
//! Unlike the golden suites — which pin canonical HASHES and are useless to
//! a consumer that needs concrete inputs — `testdata/contract/
//! pad-burst-fixtures.yaml` carries RAW `(buttons, hold_frames)` segment
//! lists per slot, exactly what a burst→input-log translation test (today:
//! exploration-orchestrator's `orch-sched` `burst_events`; eventually the
//! hypervisor-side validator) needs to replay. Every fixture regenerates
//! deterministically from (config, seed) recorded alongside it; the verify
//! test below proves the committed file matches the current sampler.
//!
//! Regenerate (same-PR workspace version bump required by the golden gate):
//! `cargo test -p synth-gen --test contract_fixtures record -- --ignored`

#[path = "common/mod.rs"]
mod common;

use synth_core::types::{burst_hash, Burst};
use synth_gen::propose::propose;

const FIXTURE_CASES: &[(u64, usize, u32)] = &[
    // (seed, k, length_hint)
    (0xC0_47_AC_01, 4, 0),
    (0xC0_47_AC_02, 4, 300),
    (0xC0_47_AC_03, 2, 60),
    (0xC0_47_AC_04, 2, 1500),
];

fn fixture_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/contract/pad-burst-fixtures.yaml")
}

fn render() -> String {
    let cfg = common::parse_and_validate(&common::base_yaml(0.25));
    let mut out = String::from(
        "# Raw pad-burst contract fixtures for downstream burst->input-log\n\
         # translation tests (offered to exploration-orchestrator /\n\
         # determinism-hypervisor). Regenerated by contract_fixtures.rs's\n\
         # record test; segments are (buttons_mask, hold_frames) against the\n\
         # console16-12btn-v1 alphabet (API.md §5.1). Every burst satisfies\n\
         # the API.md §1 invariants.\n\
         button_alphabet: console16-12btn-v1\ncases:\n",
    );
    for &(seed, k, length_hint) in FIXTURE_CASES {
        let ctx = common::ctx_free("contract-node");
        let (results, _) = propose(&cfg, &ctx, k, length_hint, seed, None);
        out.push_str(&format!(
            "  - seed: {seed}\n    k: {k}\n    length_hint: {length_hint}\n    slots:\n"
        ));
        for r in &results {
            #[allow(irrefutable_let_patterns)]
            let Burst::Pad(pad) = &r.burst
            else {
                unreachable!("pad model only in v1")
            };
            out.push_str(&format!(
                "      - burst_id: {}\n        segments: [",
                common::hex(&burst_hash(&r.burst))
            ));
            for (i, s) in pad.segments.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(&format!("[{}, {}]", s.buttons, s.hold_frames));
            }
            out.push_str("]\n");
        }
    }
    out
}

/// The committed fixture file must match what the current sampler emits —
/// the same golden discipline as the hash suites, but with raw segments so
/// downstream repos can consume them.
#[test]
fn contract_fixtures_match_committed_file() {
    let committed = std::fs::read_to_string(fixture_path())
        .expect("read testdata/contract/pad-burst-fixtures.yaml");
    assert_eq!(
        committed,
        render(),
        "contract fixtures drifted from the sampler; if the change is \
         intentional, re-record and bump the workspace version in the same PR"
    );
}

#[test]
#[ignore = "record mode: regenerates testdata/contract/pad-burst-fixtures.yaml"]
fn record_contract_fixtures() {
    let path = fixture_path();
    std::fs::create_dir_all(path.parent().unwrap()).expect("mkdir testdata/contract");
    std::fs::write(&path, render()).expect("write contract fixtures");
    println!("wrote {}", path.display());
}
