[package]
name = "synth-gen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
synth-core = { workspace = true }
synth-pad = { workspace = true }
rand_core = { workspace = true }
rand_chacha = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
statrs = { workspace = true }
blake3 = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
